In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('books.csv')

df.shape

(1000, 9)

In [14]:
df.head()

,Title,Price,Rating,Availability,Link,UPC,Stock Count,Category,Description
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...,a897fe39b1053632,22,Poetry,It's hard to imagine a world without A Light i...
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...,90fa61229261140a,20,Historical Fiction,"""Erotic and absorbing...Written with starling ..."
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...,6957f44c3847a760,20,Fiction,"Dans une France assez proche de la nôtre, un h..."
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...,e00eb4fd7b871a48,20,Mystery,"WICKED above her hipbone, GIRL across her hear..."
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...,4165285e1663650f,20,History,From a renowned historian comes a groundbreaki...

In [15]:
df.columns

Index(['Title', 'Price', 'Rating', 'Availability', 'Link', 'UPC',
       'Stock Count', 'Category', 'Description'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1000 non-null   str
 1   Price         1000 non-null   float64
 2   Rating        1000 non-null   int64
 3   Availability  1000 non-null   str
 4   Link          1000 non-null   str
 5   UPC           1000 non-null   str
 6   Stock Count   1000 non-null   int64
 7   Category      1000 non-null   str
 8   Description   998 non-null    str
dtypes: float64(1), int64(2), str(6)
memory usage: 1.6 MB

In [17]:
sorted(df["Category"].value_counts().index.to_list())

['Academic',
 'Add a comment',
 'Adult Fiction',
 'Art',
 'Autobiography',
 'Biography',
 'Business',
 'Childrens',
 'Christian',
 'Christian Fiction',
 'Classics',
 'Contemporary',
 'Crime',
 'Cultural',
 'Default',
 'Erotica',
 'Fantasy',
 'Fiction',
 'Food and Drink',
 'Health',
 'Historical',
 'Historical Fiction',
 'History',
 'Horror',
 'Humor',
 'Music',
 'Mystery',
 'New Adult',
 'Nonfiction',
 'Novels',
 'Paranormal',
 'Parenting',
 'Philosophy',
 'Poetry',
 'Politics',
 'Psychology',
 'Religion',
 'Romance',
 'Science',
 'Science Fiction',
 'Self Help',
 'Sequential Art',
 'Short Stories',
 'Spirituality',
 'Sports and Games',
 'Suspense',
 'Thriller',
 'Travel',
 'Womens Fiction',
 'Young Adult']

In [18]:
orders_df = pd.read_csv('orders_cleaned.csv')

In [22]:
orders_df.head()
orders_df['total_price'] = orders_df['quantity'] * orders_df["unit_price"]

In [23]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       18 non-null     int64
 1   order_date     18 non-null     str
 2   customer_name  18 non-null     str
 3   product        18 non-null     str
 4   category       18 non-null     str
 5   quantity       18 non-null     float64
 6   unit_price     18 non-null     float64
 7   status         18 non-null     str
 8   total_price    18 non-null     float64
dtypes: float64(3), int64(1), str(5)
memory usage: 2.3 KB

In [33]:
completed = orders_df[orders_df["status"] == 'Completed']

category_revenue = completed.groupby("category")["total_price"].sum().sort_values()

category_revenue.max()

np.float64(293.88)

In [29]:
completed.head()

Empty DataFrame
Columns: [order_id, order_date, customer_name, product, category, quantity, unit_price, status, total_price]
Index: []